name: Deploy Backend API

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies (to validate build)
        run: npm install

      - name: Deploy on VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            # Go to app dir or create if missing
            mkdir -p ~/app
            cd ~/app

            # Pull latest code from repo
            if [ -d ".git" ]; then
              git reset --hard
              git pull
            else
              git clone https://github.com/${{ github.repository }} .
            fi

            # Install dependencies
            npm install

            # Restart server
            pkill -f "node server.js" || true
            nohup sudo node server.js > output.log 2>&1 &